from pathlib import Path

# Scheduler
COLLECTOR_INTERVAL_MINUTES = 10
VISIT_HOURS_START = 6
VISIT_HOURS_END = 22

# Rollout
ROLLOUT_HOURS = 16
ROLLOUT_LIMIT = ROLLOUT_HOURS * (60 // COLLECTOR_INTERVAL_MINUTES) + 1

# Storage
DB_FILE = Path("data.db")
CSV_FILE = Path("data.csv")
DEFAULT_QUERY_LIMIT = 200